CREATE TABLE USUARIOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    ESTADO BOOLEAN DEFAULT TRUE,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);  